### ISSUE TITLE
cant connect torrentleech anymore

### ISSUE THREAD

**Issue by Ombouwleusden** [pymedusa/medusa.github.io#449] opened 2023-04-17 18:48 UTC
2023-04-17 20:38:42 INFO	APIv2-Thread :: [6b37ad0] Unknown exception in url https://www.torrentleech.org/torrents/browse/list/categories/26,27,32,34,35,44/orderby/added/order/desc/ Error: Unable to find Cloudflare cookies. Does the site actually have Cloudflare IUAM (I'm Under Attack Mode) enabled?
2023-04-17 20:36:35 INFO	APIv2-Thread-2 :: [6b37ad0] Unknown exception in url https://www.torrentleech.org/torrents/browse/list/categories/26,27,32,34,35,44/orderby/added/order/desc/ Error: Unable to find Cloudflare cookies. Does the site actually have Cloudflare IUAM (I'm Under Attack Mode) enabled?

**Comment by medariox** [comment] 2023-05-20 12:28
Duplicate of https://github.com/pymedusa/Medusa/issues/11211

**Closed by medariox** 2023-05-20 12:28 UTC
